version: "3"

services:
  mongodb:
    image: mongo:5.0.7
    container_name: sharenergy_db
    volumes:
      - ./:/app
    restart: always
    ports:
      # Garanta que não haverá conflitos de porta com um mongodb que esteja
      # rodando localmente
      - 27017:27017